### PR TITLE
Adding changes in swiftproxy_config.go for  node_timeout to 90 sec.

### PR DESCRIPTION
**Pull request by vijayrap**
Adding changes in swiftproxy_config.go for  node_timeout to 90 sec.

### CODE REVIEW

**Review by cijohnson — APPROVED** [review]

**Comment by vijayrap** [comment]
check HA

**Comment by vijayrap** [comment]
check

**Comment by vijayrap** [comment]
check

**Comment by vijayrap** [comment]
check

**Comment by vijayrap** [comment]
check HA

**Review by cijohnson — APPROVED** [review]

**Comment by vijayrap** [comment]
Check HA

**Comment by vijayrap** [comment]
check

**Comment by vijayrap** [comment]
check

**Comment by vijayrap** [comment]
recheck

**Comment by vijayrap** [comment]
recheck

**Comment by vijayrap** [comment]
recheck ha

**Comment by vijayrap** [comment]
recheck

**Comment by vijayrap** [comment]
recheck

**Pull request merged**
