### PR TITLE
Adding changes to R2011, these update is to add contrailstatusmonitor…

### PR DESCRIPTION
**Pull request by vijayrap**
… to R2011.

Signed-off-by: root <root@5a10s3-node4.englab.juniper.net>

### CODE REVIEW

**Comment by vijayrap** [comment]
recheck ha

**Comment by vijayrap** [comment]
recheck

**Comment by vijayrap** [comment]
recheck ha

**Comment by vijayrap** [comment]
recheck aio

**Review by vvaitla-juni — APPROVED** [review]
I haven't reviewed files, based on vijay, as it is similar to previous commit files approving this to unblock him

**Comment by vijayrap** [comment]
recheck

**Review by rkoverzin — APPROVED** [review]

**Pull request merged**
