### PR TITLE
Openshift readme update (#482)

### PR DESCRIPTION
**Pull request by psykulsk**
* 2011 readme updates

* Update openshift readme with a working multiline command

### CODE REVIEW

**Review by katrybacka — APPROVED** [review]

**Review by kaweue — APPROVED** [review]

**Review by Dysproz — APPROVED** [review]

**Review by Janek3d — APPROVED** [review]

**Comment by psykulsk** [comment]
recheck ha

**Comment by psykulsk** [comment]
recheck ha

**Comment by psykulsk** [comment]
recheck ha

**Comment by psykulsk** [comment]
recheck ha

**Pull request merged**
