### PR TITLE
[CEM-18672]: Rmoved throwing panic code

### PR DESCRIPTION
**Pull request by leonidre**
Replaced throwing panic code with logging and returning error. Replaced logging using fmt with log

### CODE REVIEW

**Comment by leonidre** [comment]
recheck

**Comment by lrebeja** [comment]
recheck

**Comment by Dysproz** [comment]
recheck ha

**Comment by Dysproz** [comment]
recheck ha

**Comment by Dysproz** [comment]
recheck ha

**Review by Dysproz — CHANGES_REQUESTED** [review]
It's bug fix to R2008 release. I think that you should make this PR into R2008 not master branch

**Comment by lrebeja** [comment]
Agree but it's based on this https://github.com/Juniper/contrail-operator/commit/5840bd542dc0100c7b6a0c9939857490c194c233 changes and we need first merge those and then mine. I'll create one more pr with both changes for 2008

**Comment by psykulsk** [comment]
@lrebeja ok, create the other one fro R2008 and we will merge it there first. 

Also, you need to rebase this PR onto the latest commit in the master branch as some fixes for the ha e2e tests have been merged recently.

**Comment by Dysproz** [comment]
In fact you don't need to make this PR into master anymore, because together with CaVA team we have a merging flow where we work on R2008 branch and then from time to time me or Piotr makes PR which merge R2008 changes into master in single PR.

**Comment by Dysproz** [comment]
Closing as this change is already merged into R2008 branch and will be merged into master with batched PR from R2008 branch

**Pull request closed without merging**
