### PR TITLE
Change rhel images to ubi images for Openshift manifests

### PR DESCRIPTION
**Pull request by Dysproz**
Because R2011 requires all images to use ubi tab then I change it for Openshift manifests.
I've checked that Openshift dpeloyment works with these tags.

### CODE REVIEW

**Review by kaweue — APPROVED** [review]

**Review by psykulsk — CHANGES_REQUESTED** [review]
Please also modify the R2011 release manifests
https://github.com/Juniper/contrail-operator/tree/R2011/deploy/openshift/releases/R2011/manifests

**Review by katrybacka — APPROVED** [review]

**Review by psykulsk — APPROVED** [review]

**Comment by Dysproz** [comment]
recheck

**Comment by kaweue** [comment]
recheck

**Comment by Dysproz** [comment]
recheck

**Comment by Dysproz** [comment]
recheck

**Comment by Dysproz** [comment]
recheck

**Comment by Dysproz** [comment]
recheck

**Comment by psykulsk** [comment]
recheck

**Comment by Dysproz** [comment]
recheck

**Comment by psykulsk** [comment]
recheck

**Comment by psykulsk** [comment]
recheck ha

**Comment by psykulsk** [comment]
recheck ha

**Comment by psykulsk** [comment]
recheck ha

**Pull request merged**
