### PR TITLE
 added modified files for contrailstatusmonitor

### PR DESCRIPTION
**Pull request by vijayrap**
added modified files for contrailstatusmonitor, More tests will be added later one by one

### CODE REVIEW

**Comment by vijayrap** [comment]
recheck

**Comment by vijayrap** [comment]
recheck ha

**Comment by vijayrap** [comment]
recheck ha.

**Comment by vijayrap** [comment]
recheck ha third time

**Comment by vijayrap** [comment]
recheck ha

**Review by vvaitla-juni — APPROVED** [review]

**Review by rkoverzin — APPROVED** [review]

**Pull request merged**
