### PR TITLE
Update operator to v0.18.2

### PR DESCRIPTION
**Pull request by kaweue**
Updating operator to newer version 0.18.2 however without updating crds versions to v1 it will require small refactor. I hope to do it in next PRs.

### CODE REVIEW

**Comment by michalskalski** [comment]
cool, that would mean that we can start use `kubebuilder:default` to set default values.

**Comment by kaweue** [comment]
> cool, that would mean that we can start use `kubebuilder:default` to set default values.

Not yet, but I hope that soon it will be possible. 
In crds in version v1 there is problem with embedded metadata structures. Basically they are ignored and not stored at kubernetes API server. It is connected to https://kubernetes.io/blog/2019/06/20/crd-structural-schema/#pruning-don-t-preserve-unknown-fields and to the fact that properties for metadata struct is not generated for some reason.

**Comment by kaweue** [comment]
recheck

**Comment by kaweue** [comment]
recheck

**Review by Dysproz — APPROVED** [review]

**Review by michalskalski — APPROVED** [review]

**Review by katrybacka — APPROVED** [review]

**Pull request merged**
